### PR TITLE
Issue 62 -> fix: blog pagination now updates content and resets scroll

### LINKED ISSUE #62: `/blog`: Bug in the pagination
Pagination broken after going from 1 to 2 and then to 3.

### PR DESCRIPTION
**Pull request by dgaitan**
closes #62

### CODE REVIEW

**Comment by dgaitan** [comment]
@onmax For some reason. I am not able to set a reviewer

File: app/slices/BlogpostsGrid/index.vue [hunk 1]
```diff
@@ -4,27 +4,38 @@ import { filter } from '@prismicio/client'
...
+watch(page, (val) => {
+  router.replace({ query: { ...route.query, page: val !== 1 ? val : undefined } })
+  window.scrollTo({ top: 0, behavior: 'smooth' })
+})
 
 const { client } = usePrismic()
 
-const { data: result } = await useAsyncData('blog_posts', async () => {
-  return await client.getByType('blog_page', {
+const result = ref<Awaited<ReturnType<typeof client.getByType>> | null>(null)
```
Comment (onmax) [inline app/slices/BlogpostsGrid/index.vue:24]:
```suggestion
import type { Content, Query } from '@prismicio/client'

const result = ref<Query<Content.BlogPageDocument<string>>>()
```

File: app/slices/BlogpostsGrid/index.vue [hunk 2]
```diff
@@ -4,27 +4,38 @@ import { filter } from '@prismicio/client'
 import ArticleMetadata from '~/components/ArticleMetadata.vue'
 
 defineProps(getSliceComponentProps<Content.BlogpostsGridSlice>())
-
 const showDrafts = import.meta.dev // TODO Change this depending on the NODE_ENV
```
Comment (onmax) [inline app/slices/BlogpostsGrid/index.vue:7]: Can we maybe move `isDev` on top and remove `showDrafts`? What do you think?

I know it is a bit messy the way I left the code 🙈

**Review by onmax — APPROVED** [review]
The code looks good. The comments I left are just to clean up the mess I left a while ago. What do you think about those?

Thank you very much!
